#!/bin/sh
if [ -z "${SBUILD_VERSION}" ] ; then
SBUILD_VERSION="0.7.7"
fi
if [ -z "${SBUILD_DIST}" ] ; then
SBUILD_DIST="http://sbuild.org/uploads/sbuild/${SBUILD_VERSION}/sbuild-${SBUILD_VERSION}-dist.zip"
fi
if [ -d ".wrapper/sbuild-${SBUILD_VERSION}" ] ; then
echo "Using SBuild ${SBUILD_VERSION}"
else
echo "Fetching SBuild ${SBUILD_VERSION}"
mkdir -p ".wrapper"
(cd .wrapper && wget "${SBUILD_DIST}")
(cd .wrapper && unzip "sbuild-${SBUILD_VERSION}-dist.zip")
chmod u+x ".wrapper/sbuild-${SBUILD_VERSION}/bin/sbuild"
fi
exec ".wrapper/sbuild-${SBUILD_VERSION}/bin/sbuild" "$@"
