on: [push, pull_request]

jobs: 
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [8, 11]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - run: sudo apt-get install gettext

      - run: ./millw -i "{__.compile,__.test}"

      - run: ./millw -i __.publishLocal $(pwd)/testRepo
